apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hipstershop
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  description: HipsterShop microservices demo
  sourceRepos:
    - https://github.com/GivenCloud/Proyecto-ArgoCD.git
  destinations:
    - namespace: hipstershop
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
