apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: miniproyecto
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  description: Miniproyecto Neoris Node.js API
  sourceRepos:
    - https://github.com/GivenCloud/Proyecto-ArgoCD.git
  destinations:
    - namespace: miniproyecto-neoris
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
