name: Build and Push to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=sha-
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # deploy:
  #   needs: build-and-push
  #   runs-on: self-hosted

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Deploy to Minikube
  #       run: |
  #         helm upgrade --install miniproyecto ./helm/miniproyecto \
  #           --namespace miniproyecto \
  #           --create-namespace \
  #           --set web.image=ghcr.io/givencloud/miniproyecto_neoris:${{ needs.build-and-push.outputs.image_tag }}

  #     - name: Wait for rollout
  #       run: kubectl rollout status deployment/web-deployment --namespace miniproyecto --timeout=120s
