apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniproyecto-neoris
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: miniproyecto
  source:
    repoURL: https://github.com/GivenCloud/Proyecto-ArgoCD.git
    targetRevision: main
    path: apps/Miniproyecto_Neoris/helm/miniproyecto
  destination:
    server: https://kubernetes.default.svc
    namespace: miniproyecto-neoris
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
